// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Account struct {
	ID            int64     `json:"id"`
	AccountNumber int64     `json:"accountNumber"`
	Owner         string    `json:"owner"`
	Balance       int64     `json:"balance"`
	Currency      string    `json:"currency"`
	CreatedAt     time.Time `json:"createdAt"`
}

type Entry struct {
	ID            int64 `json:"id"`
	AccountNumber int64 `json:"accountNumber"`
	// it can be positve or negative value
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
}

type Transfer struct {
	ID                int64 `json:"id"`
	FromAccountNumber int64 `json:"fromAccountNumber"`
	ToAccountNumber   int64 `json:"toAccountNumber"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashedPassword"`
	FullName          string    `json:"fullName"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"passwordChangedAt"`
	CreatedAt         time.Time `json:"createdAt"`
}
