// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccounts(ctx context.Context, arg CreateAccountsParams) (Account, error)
	CreateEntries(ctx context.Context, arg CreateEntriesParams) (Entry, error)
	CreateTransfers(ctx context.Context, arg CreateTransfersParams) (Transfer, error)
	Createuser(ctx context.Context, arg CreateuserParams) (User, error)
	DeleteAccount(ctx context.Context, accountNumber int64) error
	GetAccount(ctx context.Context, accountNumber int64) (Account, error)
	GetAccountforupdate(ctx context.Context, accountNumber int64) (Account, error)
	GetEntries(ctx context.Context, accountNumber int64) (Entry, error)
	GetTransfers(ctx context.Context, id int64) (Transfer, error)
	Getuser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
